apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: estacionamento
spec:
  type: NodePort
  ports:
  - port: 1433
    targetPort: 1433
    nodePort: 31000
    protocol: TCP
    name: sql
  selector:
    app: sqlserver
