apiVersion: v1
kind: Service
metadata:
  name: api-estacionamento-service
  namespace: estacionamento
spec:
  selector:
    application: api-estacionamento
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31001
  type: NodePort
